// Generated by CoffeeScript 1.6.3
describe("Test of Photo Jigsaw Puzzle Widget", function() {
  beforeEach(function() {
    return this.puzzle = new PuzzleApp();
  });
  return describe("App Creation Test", function() {
    return it("should create a PuzzleApp object", function() {
      expect(this.puzzle).toBeDefined;
      return expect(this.puzzle).toEqual(jasmine.any(PuzzleApp));
    });
  });
});
